# Generated by Django 6.0 on 2025-12-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(db_table='user_followers', null=True, related_name='followers', to='users.user'),
        ),
    ]
