# Generated by Django 6.0 on 2025-12-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followee', models.ForeignKey(db_column='followee_id', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.user')),
                ('follower', models.ForeignKey(db_column='follower_id', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.user')),
            ],
            options={
                'db_table': 'user_followers',
                'constraints': [models.UniqueConstraint(fields=('follower', 'followee'), name='unique_follow_relation'), models.CheckConstraint(condition=models.Q(('follower', models.F('followee')), _negated=True), name='prevent_self_follow')],
            },
        ),
    ]
