# Generated by Django 6.0 on 2025-12-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
