# Generated by Django 6.0 on 2025-12-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
