# Generated by Django 6.0 on 2025-12-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_status'),
        ('tags', '0001_initial'),
        ('users', '0002_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='users.user'),
        ),
        migrations.AddField(
            model_name='article',
            name='favorites',
            field=models.ManyToManyField(db_table='favorite_articles', null=True, related_name='favorite_articles', to='users.user'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(db_table='article_tags', null=True, related_name='article_tags', to='tags.tag'),
        ),
    ]
