# Generated by Django 6.0 on 2025-12-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_author_alter_article_status'),
        ('tags', '0001_initial'),
        ('users', '0004_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='favorites',
            field=models.ManyToManyField(db_table='favorite_articles', related_name='favorite_articles', to='users.user'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(db_table='article_tags', related_name='article_tags', to='tags.tag'),
        ),
    ]
