# Generated by Django 6.0 on 2025-12-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author_article_favorites_article_tags'),
        ('comments', '0001_initial'),
        ('users', '0002_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(db_column='article_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.user'),
        ),
    ]
