# Generated by Django 6.0 on 2025-12-22 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_article_comment_author'),
        ('users', '0004_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='users.user'),
        ),
    ]
