TITLE_MAX_LENGTH = 150
SLUG_MAX_LENGTH = 150
DESCRIPTION_MAX_LENGTH = 255
STATUS_DRAFT = 1
STATUS_PUBLISHED = 2
TITLE_MIN_LENGTH = 10
DESCRIPTION_MIN_LENGTH = 10
BODY_MIN_LENGTH = 10
STATUS_CHOICES = (
    (STATUS_DRAFT, 'Draft'),
    (STATUS_PUBLISHED, 'Published'),
)
LIST_LIMIT_DEFAULT = 10
